version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          start: npm run dev
          wait-on: http://localhost:8080
          record: true
          command: cypress run --record --key cd7662bf-1c46-4172-84f3-2c329da84463
          group: chrome
          browser: chrome